server:
  port: 3333
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: sudhansushekharsahoo143@gmail.com
    password: shekhar7540
    properties.mail.smtp:
                      auth: ture
                      starttls:
                         enable: true      
  jpa:
    database: ORACLE
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    platform: oracle
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger